### ISSUE TITLE
Confusion with single site extraction

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/site#6]
The site index argument of `single_site()` caused some confusion. 
Requests for named-filtering, although this may be too -custom/hand-holding

**Comment by htopazian** [comment]
I am getting around this now by creating a dataframe of all of the possible ISOs, admin names, and urban/rural classifications. Then assigning a row number 'index' and returning. Then I can easily match the index number with my shapefiles or sites of interest by name. We could include an example in a vignette of how to do this with just one country to easily pull out the indices of a couple admin units?

``` 
# make a list of all foresite package site ISOs and admin1 names with index
site_lookup <- function(ISO){
  
  # pull site
  site <- eval(parse(text = paste0("foresite::", ISO)))
  
  # extract ISO, admin1 name, and urban / rural vars
  ISO <- site$site$iso3c
  admin <- site$site$name_1
  type <- site$site$urban_rural
  
  # make dataset and index by row
  site_list <- tibble(ID_0 = ISO, NAME_1 = admin, type = type) |>
    mutate(index = row_number())
  
  return(site_list)

}

all_sites <- map_dfr(unique(countries$ID_0), site_lookup)
```

**Comment by pwinskill** [comment]
Just fyi - some of that step is done for you in `site_file$sites`
